"""
tracker.py

ConversationCostTracker -- simulates a growing chat conversation and
tracks the CUMULATIVE token cost at every turn.

Key idea (from earlier discussion): LLM APIs are stateless. To "remember"
a conversation, the entire message history must be resent on every
single call. This means the cost of turn N isn't just the cost of the
new message -- it's the cost of resending turns 1 through N-1 as well.
This tool makes that growth visible.

Token counting can use either:
    - approximate_tokens()  -- the len(text) // 4 heuristic (default,
      zero dependencies, good enough for seeing the COST CURVE shape)
    - bpe_tokens()           -- real subword counts via tiktoken,
      gracefully falling back to the approximation if unavailable

Pass use_bpe=True to ConversationCostTracker to switch to real BPE
counts; leave it False (the default) to use the simple heuristic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Generator, Literal, TypedDict

from tokenizer import approximate_tokens, bpe_tokens

Role = Literal["user", "assistant", "system"]


class Message(TypedDict):
    role: Role
    content: str


class TurnCost(TypedDict):
    turn: int
    role: Role
    new_tokens: int
    cumulative_tokens: int
    cumulative_cost: float
    exact: bool
    note: str


@dataclass
class ConversationCostTracker:
    input_price_per_token: float = 3.00 / 1_000_000   # default: Claude Sonnet-ish input pricing
    output_price_per_token: float = 15.00 / 1_000_000  # default: Claude Sonnet-ish output pricing
    context_window_limit: int = 200_000
    use_bpe: bool = False   # False = approximate_tokens(), True = real BPE via tiktoken
    messages: list[Message] = field(default_factory=list)

    def __repr__(self) -> str:
        return (
            f"ConversationCostTracker(turns={len(self.messages)}, "
            f"total_tokens={self.total_tokens_so_far()}, "
            f"use_bpe={self.use_bpe})"
        )

    # ---- token counting, swappable between the two strategies ---------
    def _count_tokens(self, text: str) -> tuple[int, bool, str]:
        if self.use_bpe:
            result = bpe_tokens(text)
            return result.token_count, result.exact, result.note

        return approximate_tokens(text), False, "approximate_tokens heuristic (len // 4)"

    # ---- adding to the conversation -----------------------------------
    def add_message(self, role: Role, content: str) -> None:
        self.messages.append(Message(role=role, content=content))

    # ---- core cumulative calculation, as a generator -------------------
    def cost_per_turn(self) -> Generator[TurnCost, None, None]:
        """
        Yields one TurnCost per message, lazily.

        Input vs. output pricing is modeled per real API call:
          - A "user" (or "system") message triggers an API call whose
            INPUT is everything sent so far -- all prior history PLUS
            this new message. That's billed at input_price_per_token.
          - An "assistant" message is the OUTPUT generated by that call.
            Only its own new tokens are billed, at output_price_per_token.
            It is NOT re-billed here as input -- that happens naturally
            on the *next* user turn, once it has become part of history.

        cumulative_tokens still reflects total tokens seen so far (useful
        for context-window tracking). cumulative_cost is the running sum
        of actual per-call costs, correctly split between input and output
        rates.
        """
        history_tokens = 0
        cumulative_cost = 0.0

        for index, message in enumerate(self.messages, start=1):
            new_tokens, exact, note = self._count_tokens(message["content"])

            if message["role"] == "assistant":
                # Generated as OUTPUT for this call -- only the new tokens.
                call_cost = new_tokens * self.output_price_per_token
            else:
                # This message + everything before it is resent as INPUT.
                call_cost = (history_tokens + new_tokens) * self.input_price_per_token

            history_tokens += new_tokens
            cumulative_cost += call_cost

            yield TurnCost(
                turn=index,
                role=message["role"],
                new_tokens=new_tokens,
                cumulative_tokens=history_tokens,
                cumulative_cost=cumulative_cost,
                exact=exact,
                note=note,
            )

    # ---- convenience wrappers built on top of the generator ------------
    def total_tokens_so_far(self) -> int:
        total = 0
        for turn in self.cost_per_turn():
            total = turn["cumulative_tokens"]
        return total

    def total_cost_so_far(self) -> float:
        # NOTE: cost is a mix of input- and output-rate charges (see
        # cost_per_turn), so it can no longer be derived as a flat
        # total_tokens * input_price_per_token. Pull the real cumulative
        # figure straight from the generator instead.
        total_cost = 0.0
        for turn in self.cost_per_turn():
            total_cost = turn["cumulative_cost"]
        return total_cost

    def context_usage_percent(self) -> float:
        return (self.total_tokens_so_far() / self.context_window_limit) * 100

    def is_near_context_limit(self, threshold_percent: float = 80.0) -> bool:
        return self.context_usage_percent() >= threshold_percent
